-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:04:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Arquitecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arquitecto` (
  `cod_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `num_colegiado` VARCHAR(45) NULL,
  `cod_facultad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_empleado`, `cod_facultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`E-A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-A` (
  `cod_edificio` INT NOT NULL,
  `cod_empleado` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `Arquitecto_cod_empleado` INT NOT NULL,
  `Arquitecto_cod_facultad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_edificio`),
  CONSTRAINT `fk_E-A_Arquitecto1`
    FOREIGN KEY (`Arquitecto_cod_empleado` , `Arquitecto_cod_facultad`)
    REFERENCES `mydb`.`Arquitecto` (`cod_empleado` , `cod_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_E-A_Arquitecto1_idx` ON `mydb`.`E-A` (`Arquitecto_cod_empleado` ASC, `Arquitecto_cod_facultad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Capataz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Capataz` (
  `cod_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`E-C`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-C` (
  `cod_edificio` INT NOT NULL,
  `cod_empleado` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `Capataz_cod_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_edificio`),
  CONSTRAINT `fk_E-C_Capataz1`
    FOREIGN KEY (`Capataz_cod_empleado`)
    REFERENCES `mydb`.`Capataz` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_E-C_Capataz1_idx` ON `mydb`.`E-C` (`Capataz_cod_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Herramienta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Herramienta` (
  `cod_herramienta` INT NOT NULL,
  `nombre_herramienta` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_herramienta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`A-H`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`A-H` (
  `cod_empleado` INT NOT NULL,
  `cod_herramienta` VARCHAR(45) NULL,
  `Herramienta_cod_herramienta` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  CONSTRAINT `fk_A-H_Herramienta1`
    FOREIGN KEY (`Herramienta_cod_herramienta`)
    REFERENCES `mydb`.`Herramienta` (`cod_herramienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_A-H_Herramienta1_idx` ON `mydb`.`A-H` (`Herramienta_cod_herramienta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Albañil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Albañil` (
  `cod_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  `cod_empleado_capataz` VARCHAR(45) NOT NULL,
  `A-H_cod_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_empleado_capataz`, `cod_empleado`),
  CONSTRAINT `fk_Albañil_A-H1`
    FOREIGN KEY (`A-H_cod_empleado`)
    REFERENCES `mydb`.`A-H` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Albañil_A-H1_idx` ON `mydb`.`Albañil` (`A-H_cod_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`E-AL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-AL` (
  `cod_edificio` INT NOT NULL,
  `cod_empleado` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `Albañil_cod_empleado_capataz` VARCHAR(45) NOT NULL,
  `Albañil_cod_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_edificio`),
  CONSTRAINT `fk_E-AL_Albañil1`
    FOREIGN KEY (`Albañil_cod_empleado_capataz` , `Albañil_cod_empleado`)
    REFERENCES `mydb`.`Albañil` (`cod_empleado_capataz` , `cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_E-AL_Albañil1_idx` ON `mydb`.`E-AL` (`Albañil_cod_empleado_capataz` ASC, `Albañil_cod_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edificio` (
  `cod_edificio` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `E-A_cod_edificio` INT NOT NULL,
  `E-C_cod_edificio` INT NOT NULL,
  `E-AL_cod_edificio` INT NOT NULL,
  PRIMARY KEY (`cod_edificio`),
  CONSTRAINT `fk_Edificio_E-A1`
    FOREIGN KEY (`E-A_cod_edificio`)
    REFERENCES `mydb`.`E-A` (`cod_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Edificio_E-C1`
    FOREIGN KEY (`E-C_cod_edificio`)
    REFERENCES `mydb`.`E-C` (`cod_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Edificio_E-AL1`
    FOREIGN KEY (`E-AL_cod_edificio`)
    REFERENCES `mydb`.`E-AL` (`cod_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Edificio_E-A1_idx` ON `mydb`.`Edificio` (`E-A_cod_edificio` ASC) VISIBLE;

CREATE INDEX `fk_Edificio_E-C1_idx` ON `mydb`.`Edificio` (`E-C_cod_edificio` ASC) VISIBLE;

CREATE INDEX `fk_Edificio_E-AL1_idx` ON `mydb`.`Edificio` (`E-AL_cod_edificio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facultad` (
  `cod_facultad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `Arquitecto_cod_empleado` INT NOT NULL,
  `Arquitecto_cod_facultad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_facultad`),
  CONSTRAINT `fk_Facultad_Arquitecto`
    FOREIGN KEY (`Arquitecto_cod_empleado` , `Arquitecto_cod_facultad`)
    REFERENCES `mydb`.`Arquitecto` (`cod_empleado` , `cod_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Facultad_Arquitecto_idx` ON `mydb`.`Facultad` (`Arquitecto_cod_empleado` ASC, `Arquitecto_cod_facultad` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
