-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:15:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `nif_tieneresponsable` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `nif_esresponsable` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`nif_tieneresponsable`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`E-E`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-E` (
  `nif_esresponsable` INT NOT NULL,
  `departamento` VARCHAR(45) NULL,
  `nif_tieneresponsable` VARCHAR(45) NOT NULL,
  `Empleado_nif_tieneresponsable` INT NOT NULL,
  PRIMARY KEY (`nif_tieneresponsable`),
  CONSTRAINT `fk_E-E_Empleado`
    FOREIGN KEY (`Empleado_nif_tieneresponsable`)
    REFERENCES `mydb`.`Empleado` (`nif_tieneresponsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_E-E_Empleado_idx` ON `mydb`.`E-E` (`Empleado_nif_tieneresponsable` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
