-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:16:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo` (
  `matricula` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conduce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conduce` (
  `matricula` INT NOT NULL,
  `codemp` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `Vehiculo_matricula` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  CONSTRAINT `fk_Conduce_Vehiculo1`
    FOREIGN KEY (`Vehiculo_matricula`)
    REFERENCES `mydb`.`Vehiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Conduce_Vehiculo1_idx` ON `mydb`.`Conduce` (`Vehiculo_matricula` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `codemp` INT NOT NULL,
  `no,bre` VARCHAR(45) NULL,
  `Conduce_matricula` INT NOT NULL,
  PRIMARY KEY (`codemp`),
  CONSTRAINT `fk_Empleado_Conduce`
    FOREIGN KEY (`Conduce_matricula`)
    REFERENCES `mydb`.`Conduce` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empleado_Conduce_idx` ON `mydb`.`Empleado` (`Conduce_matricula` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
