-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:17:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Edicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edicion` (
  `numero` INT NOT NULL,
  `año` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `Autor` INT NOT NULL,
  PRIMARY KEY (`Autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `isbn` INT NOT NULL,
  `titulo_principal` VARCHAR(45) NOT NULL,
  `subtitulo` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(45) NOT NULL,
  `idioma` VARCHAR(45) NOT NULL,
  `Edicion_numero` INT NOT NULL,
  `Autor_Autor` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  CONSTRAINT `fk_Libro_Edicion`
    FOREIGN KEY (`Edicion_numero`)
    REFERENCES `mydb`.`Edicion` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_Autor1`
    FOREIGN KEY (`Autor_Autor`)
    REFERENCES `mydb`.`Autor` (`Autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Libro_Edicion_idx` ON `mydb`.`Libro` (`Edicion_numero` ASC) VISIBLE;

CREATE INDEX `fk_Libro_Autor1_idx` ON `mydb`.`Libro` (`Autor_Autor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
