-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:19:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`P-P`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`P-P` (
  `cod_pieza_contiene` INT NOT NULL,
  `cod_pieza_contenido` VARCHAR(45) NULL,
  `funcion` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pieza_contiene`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pieza` (
  `cod_pieza` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `P-P_cod_pieza_contiene` INT NOT NULL,
  PRIMARY KEY (`cod_pieza`),
  CONSTRAINT `fk_Pieza_P-P`
    FOREIGN KEY (`P-P_cod_pieza_contiene`)
    REFERENCES `mydb`.`P-P` (`cod_pieza_contiene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pieza_P-P_idx` ON `mydb`.`Pieza` (`P-P_cod_pieza_contiene` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
