-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:20:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piloto` (
  `nif` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
  `nombre_ciudad` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `numero_habitantes` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre_ciudad`, `pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avion` (
  `cod_avion` INT NOT NULL,
  `nombre_avion` VARCHAR(45) NULL,
  `numero_motores` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_avion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`P-C-A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`P-C-A` (
  `nif` INT NOT NULL,
  `nombre_ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NOT NULL,
  `cod_avion` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  `Avion_cod_avion` INT NOT NULL,
  `Piloto_nif` INT NOT NULL,
  `Ciudad_nombre_ciudad` INT NOT NULL,
  `Ciudad_pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nif`, `pais`),
  CONSTRAINT `fk_P-C-A_Avion1`
    FOREIGN KEY (`Avion_cod_avion`)
    REFERENCES `mydb`.`Avion` (`cod_avion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P-C-A_Piloto1`
    FOREIGN KEY (`Piloto_nif`)
    REFERENCES `mydb`.`Piloto` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P-C-A_Ciudad1`
    FOREIGN KEY (`Ciudad_nombre_ciudad` , `Ciudad_pais`)
    REFERENCES `mydb`.`Ciudad` (`nombre_ciudad` , `pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_P-C-A_Avion1_idx` ON `mydb`.`P-C-A` (`Avion_cod_avion` ASC) VISIBLE;

CREATE INDEX `fk_P-C-A_Piloto1_idx` ON `mydb`.`P-C-A` (`Piloto_nif` ASC) VISIBLE;

CREATE INDEX `fk_P-C-A_Ciudad1_idx` ON `mydb`.`P-C-A` (`Ciudad_nombre_ciudad` ASC, `Ciudad_pais` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
