-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:21:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `nif` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `cod_piso` INT NOT NULL,
  `calle` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `planta` VARCHAR(45) NULL,
  `puerta` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_piso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`P-P`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`P-P` (
  `nif` INT NOT NULL,
  `cod_piso` VARCHAR(45) NULL,
  `precio_alquiler` VARCHAR(45) NULL,
  `Persona_nif` INT NOT NULL,
  `Piso_cod_piso` INT NOT NULL,
  PRIMARY KEY (`nif`),
  CONSTRAINT `fk_P-P_Persona`
    FOREIGN KEY (`Persona_nif`)
    REFERENCES `mydb`.`Persona` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_P-P_Piso1`
    FOREIGN KEY (`Piso_cod_piso`)
    REFERENCES `mydb`.`Piso` (`cod_piso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_P-P_Persona_idx` ON `mydb`.`P-P` (`Persona_nif` ASC) VISIBLE;

CREATE INDEX `fk_P-P_Piso1_idx` ON `mydb`.`P-P` (`Piso_cod_piso` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
