-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:22:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BENEFICIARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BENEFICIARIO` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POLIZA_VIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POLIZA_VIDA` (
  `numero` INT NOT NULL,
  `BENEFICIARIO_dni` INT NOT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `fk_POLIZA_VIDA_BENEFICIARIO1`
    FOREIGN KEY (`BENEFICIARIO_dni`)
    REFERENCES `mydb`.`BENEFICIARIO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_POLIZA_VIDA_BENEFICIARIO1_idx` ON `mydb`.`POLIZA_VIDA` (`BENEFICIARIO_dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`POLIZA_AUTOMOVIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POLIZA_AUTOMOVIL` (
  `numero` INT NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numero`, `matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POLIZA_VIVIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POLIZA_VIVIENDA` (
  `numero` INT NOT NULL,
  `domicilio` VARCHAR(45) NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POLIZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POLIZA` (
  `numero` INT NOT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_.fin` VARCHAR(45) NULL,
  `POLIZA_VIDA_numero` INT NOT NULL,
  `POLIZA_AUTOMOVIL_numero` INT NOT NULL,
  `POLIZA_VIVIENDA_numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `fk_POLIZA_POLIZA_VIDA`
    FOREIGN KEY (`POLIZA_VIDA_numero`)
    REFERENCES `mydb`.`POLIZA_VIDA` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POLIZA_POLIZA_AUTOMOVIL1`
    FOREIGN KEY (`POLIZA_AUTOMOVIL_numero`)
    REFERENCES `mydb`.`POLIZA_AUTOMOVIL` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_POLIZA_POLIZA_VIVIENDA1`
    FOREIGN KEY (`POLIZA_VIVIENDA_numero`)
    REFERENCES `mydb`.`POLIZA_VIVIENDA` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_POLIZA_POLIZA_VIDA_idx` ON `mydb`.`POLIZA` (`POLIZA_VIDA_numero` ASC) VISIBLE;

CREATE INDEX `fk_POLIZA_POLIZA_AUTOMOVIL1_idx` ON `mydb`.`POLIZA` (`POLIZA_AUTOMOVIL_numero` ASC) VISIBLE;

CREATE INDEX `fk_POLIZA_POLIZA_VIVIENDA1_idx` ON `mydb`.`POLIZA` (`POLIZA_VIVIENDA_numero` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
