-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:23:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`P-G`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`P-G` (
  `cod_profesor` INT NOT NULL,
  `cod_grupo` VARCHAR(45) NOT NULL,
  `año_academico` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesor` (
  `cod_profesor` INT NOT NULL,
  `nif` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `P-G_cod_profesor` INT NOT NULL,
  PRIMARY KEY (`cod_profesor`),
  CONSTRAINT `fk_Profesor_P-G`
    FOREIGN KEY (`P-G_cod_profesor`)
    REFERENCES `mydb`.`P-G` (`cod_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Profesor_P-G_idx` ON `mydb`.`Profesor` (`P-G_cod_profesor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`GrupoAlumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GrupoAlumnos` (
  `cod_grupo` INT NOT NULL,
  `curso` VARCHAR(45) NULL,
  `P-G_cod_profesor` INT NOT NULL,
  PRIMARY KEY (`cod_grupo`),
  CONSTRAINT `fk_GrupoAlumnos_P-G1`
    FOREIGN KEY (`P-G_cod_profesor`)
    REFERENCES `mydb`.`P-G` (`cod_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_GrupoAlumnos_P-G1_idx` ON `mydb`.`GrupoAlumnos` (`P-G_cod_profesor` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
