-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 22:24:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `cod_empresa` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `cod_pais` INT NOT NULL,
  `nombre_pais` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`D-P`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`D-P` (
  `cod_empleado` INT NOT NULL,
  `cod_pais` VARCHAR(45) NULL,
  `Pais_cod_pais` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  CONSTRAINT `fk_D-P_Pais1`
    FOREIGN KEY (`Pais_cod_pais`)
    REFERENCES `mydb`.`Pais` (`cod_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_D-P_Pais1_idx` ON `mydb`.`D-P` (`Pais_cod_pais` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Director` (
  `cod_empleado` INT NOT NULL,
  `D-P_cod_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  CONSTRAINT `fk_Director_D-P1`
    FOREIGN KEY (`D-P_cod_empleado`)
    REFERENCES `mydb`.`D-P` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Director_D-P1_idx` ON `mydb`.`Director` (`D-P_cod_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Lenguaje-Programacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lenguaje-Programacion` (
  `cod_lenguaje` INT NOT NULL,
  `nombre_lenguaje` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_lenguaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`P-L-P`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`P-L-P` (
  `cod_empleado` INT NOT NULL,
  `cod_lenaguaje` VARCHAR(45) NULL,
  `Lenguaje-Programacion_cod_lenguaje` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  CONSTRAINT `fk_P-L-P_Lenguaje-Programacion1`
    FOREIGN KEY (`Lenguaje-Programacion_cod_lenguaje`)
    REFERENCES `mydb`.`Lenguaje-Programacion` (`cod_lenguaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_P-L-P_Lenguaje-Programacion1_idx` ON `mydb`.`P-L-P` (`Lenguaje-Programacion_cod_lenguaje` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Programador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Programador` (
  `cod_empleado` INT NOT NULL,
  `P-L-P_cod_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  CONSTRAINT `fk_Programador_P-L-P1`
    FOREIGN KEY (`P-L-P_cod_empleado`)
    REFERENCES `mydb`.`P-L-P` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Programador_P-L-P1_idx` ON `mydb`.`Programador` (`P-L-P_cod_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Auxiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auxiliar` (
  `cod_empleado` INT NOT NULL,
  `num_pulsaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`E-E`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-E` (
  `cod_empresa` INT NOT NULL,
  `cod_empleado` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `Empresa_cod_empresa` INT NOT NULL,
  PRIMARY KEY (`cod_empresa`),
  CONSTRAINT `fk_E-E_Empresa1`
    FOREIGN KEY (`Empresa_cod_empresa`)
    REFERENCES `mydb`.`Empresa` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_E-E_Empresa1_idx` ON `mydb`.`E-E` (`Empresa_cod_empresa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado-de-empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado-de-empresa` (
  `cod_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `Director_cod_empleado` INT NOT NULL,
  `Programador_cod_empleado` INT NOT NULL,
  `Auxiliar_cod_empleado` INT NOT NULL,
  `E-E_cod_empresa` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  CONSTRAINT `fk_Empleado-de-empresa_Director`
    FOREIGN KEY (`Director_cod_empleado`)
    REFERENCES `mydb`.`Director` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado-de-empresa_Programador1`
    FOREIGN KEY (`Programador_cod_empleado`)
    REFERENCES `mydb`.`Programador` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado-de-empresa_Auxiliar1`
    FOREIGN KEY (`Auxiliar_cod_empleado`)
    REFERENCES `mydb`.`Auxiliar` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado-de-empresa_E-E1`
    FOREIGN KEY (`E-E_cod_empresa`)
    REFERENCES `mydb`.`E-E` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empleado-de-empresa_Director_idx` ON `mydb`.`Empleado-de-empresa` (`Director_cod_empleado` ASC) VISIBLE;

CREATE INDEX `fk_Empleado-de-empresa_Programador1_idx` ON `mydb`.`Empleado-de-empresa` (`Programador_cod_empleado` ASC) VISIBLE;

CREATE INDEX `fk_Empleado-de-empresa_Auxiliar1_idx` ON `mydb`.`Empleado-de-empresa` (`Auxiliar_cod_empleado` ASC) VISIBLE;

CREATE INDEX `fk_Empleado-de-empresa_E-E1_idx` ON `mydb`.`Empleado-de-empresa` (`E-E_cod_empresa` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Paquete-Ofimatico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paquete-Ofimatico` (
  `cod_paquete` INT NOT NULL,
  `nombre_paquete` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_paquete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`H-A`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`H-A` (
  `cod_empleado` INT NOT NULL,
  `cod_paquete` VARCHAR(45) NULL,
  `Auxiliar_cod_empleado` INT NOT NULL,
  `Paquete-Ofimatico_cod_paquete` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`),
  CONSTRAINT `fk_H-A_Auxiliar1`
    FOREIGN KEY (`Auxiliar_cod_empleado`)
    REFERENCES `mydb`.`Auxiliar` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_H-A_Paquete-Ofimatico1`
    FOREIGN KEY (`Paquete-Ofimatico_cod_paquete`)
    REFERENCES `mydb`.`Paquete-Ofimatico` (`cod_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_H-A_Auxiliar1_idx` ON `mydb`.`H-A` (`Auxiliar_cod_empleado` ASC) VISIBLE;

CREATE INDEX `fk_H-A_Paquete-Ofimatico1_idx` ON `mydb`.`H-A` (`Paquete-Ofimatico_cod_paquete` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
